language: python
python:
- '3.6'
branches:
  only:
  - master
  - develop
services:
- postgresql
env:
- DJANGO=2.0 DB=postgres
global:
- PGPORT=5432
before_install:
- cd decide
install:
- pip install selenium
- pip install -r ../requirements.txt
before_script:
- cp local_settings.travis.py local_settings.py
- psql -U postgres -c "create user decide password 'decide'" 
- psql -U postgres -c "create database test_decide owner decide" 
- psql -U postgres -c "ALTER USER decide CREATEDB"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
addons:
  postgresql: '9.6'
