language: python
python:
- '3.6'
branches:
  only:
  - master
  - develop
services:
- postgresql
env:
- DJANGO=2.0 DB=postgres
global:
- PGPORT=5432
before_install:
- sudo apt update
- sudo apt install chromium-chromedriver
- cd decide
install:
- pip install selenium
- pip install -r ../requirements.txt
before_script:
- cp local_settings.travis.py local_settings.py
- cd decide
- cp -f travis_settings.py settings.py
- cd ..
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test voting
addons:
  postgresql: '9.6'
  chrome: stable
deploy:
  - provider: heroku
    app: decide-prueba-travis
    strategy: git
    api_key:
      secure: DKe6XIy6PdBvoNflTc6N7bOvGjtgfkM4uXNAjUl8nKU6qLNsYRr4Ujs1UFZcMaF6/yChPm2GWlIFKKfk+rjvu6T8oW2woS1361gexFn59lRYJSVJi79j+07rixBHw6zWBlAXwJGKtfSTKaM/tLkvAwZpJWHZXkQDqc9LB+I4wVrmDAVcXWXfXoih3jdZaW2AgfKDZH7BNVfPgJvSE/NOVT7CljKV/eTLLHhRUA2kBh5ZeSQUgwzOggXuiLCRhPTBnIsG+75p8wLFePE6xaGk7VWpoRzkMwc/ULYJpajFJ2y9qeYxL7Iq0G9UWZI+sJb8TuC7sVxVLUiQEQ6bSewCqpkomrZxK8nTeM0Xvf7ueLcLLFjPiozs+uKUOjUAmrabt0FDITCOs3CNTuAz5MYQW5ri0IsM34O7nn98rJ3RlPqZMb84FIGTM9QvnKzbKnmxGos4hTmnw7ylpVC/pmfaFgfysmzZu/S0wuVGOuMmqmrI/7AiGpzRdOisbTA4RUC9CZtjIsjY4DOljiRjrLHgaUwMjGIc98pTwmQpcbWVPsW3HHktGelugu7BzC+eN+jgp1r1KAJMcNd4z8MlA6S0gQmJHOgPwSMH9jbvgKpxnfFm79BMRW5F1ARItDWDdGvANDG8vHXo3g19c4H6G0T3Ruc+lgws2/ud37OJVwSJvl4=
    on:
      branch: develop
  - provider: heroku
    app: decide-prueba-travis-otro
    strategy: git
    api_key:
      secure: DKe6XIy6PdBvoNflTc6N7bOvGjtgfkM4uXNAjUl8nKU6qLNsYRr4Ujs1UFZcMaF6/yChPm2GWlIFKKfk+rjvu6T8oW2woS1361gexFn59lRYJSVJi79j+07rixBHw6zWBlAXwJGKtfSTKaM/tLkvAwZpJWHZXkQDqc9LB+I4wVrmDAVcXWXfXoih3jdZaW2AgfKDZH7BNVfPgJvSE/NOVT7CljKV/eTLLHhRUA2kBh5ZeSQUgwzOggXuiLCRhPTBnIsG+75p8wLFePE6xaGk7VWpoRzkMwc/ULYJpajFJ2y9qeYxL7Iq0G9UWZI+sJb8TuC7sVxVLUiQEQ6bSewCqpkomrZxK8nTeM0Xvf7ueLcLLFjPiozs+uKUOjUAmrabt0FDITCOs3CNTuAz5MYQW5ri0IsM34O7nn98rJ3RlPqZMb84FIGTM9QvnKzbKnmxGos4hTmnw7ylpVC/pmfaFgfysmzZu/S0wuVGOuMmqmrI/7AiGpzRdOisbTA4RUC9CZtjIsjY4DOljiRjrLHgaUwMjGIc98pTwmQpcbWVPsW3HHktGelugu7BzC+eN+jgp1r1KAJMcNd4z8MlA6S0gQmJHOgPwSMH9jbvgKpxnfFm79BMRW5F1ARItDWDdGvANDG8vHXo3g19c4H6G0T3Ruc+lgws2/ud37OJVwSJvl4=
    on:
      branch: develop
