# Generated by Django 2.0 on 2021-01-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210117_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='yes_or_no_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.YesOrNoQuestion'),
        ),
    ]
