# Generated by Django 2.0 on 2021-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='url',
            field=models.CharField(help_text='http://localhost:8000/booth/', max_length=40),
        ),
    ]
