# Generated by Django 2.0 on 2021-01-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20210106_1529'),
        ('voting', '0005_auto_20210101_1813'),
    ]

    operations = [
    ]
