# Generated by Django 2.0 on 2021-01-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_merge_20210106_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('preference', models.CharField(blank=True, choices=[('B', '1'), ('M', '2'), ('A', '3')], max_length=1)),
            ],
        ),
    ]
