# Generated by Django 2.0 on 2021-01-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_orderquestion'),
        ('voting', '0009_auto_20210106_2332'),
    ]

    operations = [
    ]
