# Generated by Django 2.0 on 2021-01-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_merge_20210117_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='orderquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.OrderQuestion'),
        ),
    ]
