# Generated by Django 2.0 on 2021-01-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_voting_orderquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='orderquestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.OrderQuestion', verbose_name='Order question'),
        ),
    ]
