# Generated by Django 2.0 on 2021-01-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_auto_20210117_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='orderquestion',
        ),
        migrations.AddField(
            model_name='voting',
            name='order_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.OrderQuestion'),
        ),
    ]
